### ISSUE TITLE
Microservice Challenge : Starter - Spring Boot

### ISSUE THREAD

**Issue by vinodmrhcl** [ERS-HCL/microservice-starter-springboot#1]
Implement Microservice Starter based in Spring Boot and add support for
- Packaging
- Deployment

**Comment by tsukhu** [comment]
@vinodmrhcl what is the differentiator in this project beyond what we get from the spring.io standard code generation?

**Comment by vinodmrhcl** [comment]
At this stage it's more or less similar but the idea is to
- first create a collections of starters around various micro service techniques and
- then add various required feature like inter service communication. transaction management within different platform etc.

**Comment by tsukhu** [comment]
It will be great to first document what is the final goal in the `README` so that the community can track this in terms of what additional value it will provide.

**Comment by vinodmrhcl** [comment]
@tsukhu - Added an initial goal/plan at below location.
https://github.com/vinodmrhcl/microservice-challenge/blob/master/README.md

**Comment by vinodmrhcl** [comment]
Added implementation and moved to merged repository
https://github.com/ERS-HCL/microservice-starter/tree/master/microservice-starter-springboot
